INSERT INTO user_role (role_name)
    VALUES  ('student'),
            ('admin');

INSERT INTO app_user (email, user_password, first_name, last_name, phone, role_id)
    VALUES  ('jordanlandberg@gmail.com', 'password', 'Jordan', 'Landberg'
                '(516)806-7753', SELECT role_id FROM user_role WHERE role_name='admin'),
            ('abood.aqrab@hotmail.com', 'password', 'Abdulah', 'Aqrabawi'
                '(951)215-1414', SELECT role_id FROM user_role WHERE role_name='admin'),
            ('carrichka@yahoo.com', 'password', 'Carri', 'Martin'
                '(303)916-0458', SELECT role_id FROM user_role WHERE role_name='admin'),
            ('blake.kruppa@revature.com', 'pass', 'Blake', 'Kruppa'
                '(587)364-9861', SELECT role_id FROM user_role WHERE role_name='admin'),
            ('phongtran@gmail.com', 'password', 'Phong', 'Tran'
                '(364)669-9753', SELECT role_id FROM user_role WHERE role_name='student'),
            ('chrispy@magic.com', 'password', 'Chris', 'Prosser'
                '(598)744-1258', SELECT role_id FROM user_role WHERE role_name='student'),
            ('jboakye@ginyuforce.org', 'password', 'Joseph', 'Boakye'
                '(635)257-1354', SELECT role_id FROM user_role WHERE role_name='student');

INSERT INTO question_category (category_name)
    VALUES  ('HTML'), ('CSS'), ('JavaScript'), ('React'), ('Redux'), ('SQL'), ('pgAdmin'), 
            ('Java'), ('Node'), ('Express'), ('AWS'), ('DevOps');

INSERT INTO question_status (status_name)
    VALUES ('Pending'), ('Approved'), ('Denied');

-- HTML QUESTIONS
INSERT INTO question (question, category_id, status_id)
    VALUES  ('What is HTML?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is an element?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is the difference between an id and a class?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How does every HTML page start?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How many elements can you add the id of "custom-id"?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How many elements can you add the class of "custom-class"?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is the format for creating a div element in JavaScript?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What does DOM stand for?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is a meta tag used for?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('Which of these is valid list syntax for creating an ordered list?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How do you link a CSS file?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How do you link a JavaScript file?', 
                SELECT category_id FROM question_category WHERE category_name = 'HTML', 
                SELECT status_id FROM question_status WHERE status_name = 'Approved');
-- HTML ANSWERS
INSERT INTO answer (answer,question_id)
    VALUES  ('HyperText Markup Language',
                SELECT question_id FROM question WHERE question = 'What is HTML?'),
            ('Hidden Token Middle Language',
                SELECT question_id FROM question WHERE question = 'What is HTML?'),
            ('Hyperlinks and Text Markup Language',
                SELECT question_id FROM question WHERE question = 'What is HTML?'),
            ('Hyper Tool Markup Language',
                SELECT question_id FROM question WHERE question = 'What is HTML?'),
            ('Everything from the start tag to an end tag',
                SELECT question_id FROM question WHERE question = 'What is an element?'),
            ('A way to style a tag',
                SELECT question_id FROM question WHERE question = 'What is an element?'),
            ('A way that you can tell a tag where it will be on a page',
                SELECT question_id FROM question WHERE question = 'What is an element?'),
            ('Air, Earth, Fire, Water',
                SELECT question_id FROM question WHERE question = 'What is an element?'),
            ('Id''s can be used only once while classes can be used multiple times',
                SELECT question_id FROM question WHERE question = 'What is the difference between an id and a class?'),
            ('Classes can be used only once while id''s can be used multiple times',
                SELECT question_id FROM question WHERE question = 'What is the difference between an id and a class?'),
            ('Id''s are used in databases for a primary key while classes are used exclusively in HTML',
                SELECT question_id FROM question WHERE question = 'What is the difference between an id and a class?'),
            ('Classes are able to be used in only a single file while id''s can be used in as many files as you want',
                SELECT question_id FROM question WHERE question = 'What is the difference between an id and a class?'),
            ('<!DOCTYPE html>',
                SELECT question_id FROM question WHERE question = 'How does every HTML page start?'),
            ('<html>',
                SELECT question_id FROM question WHERE question = 'How does every HTML page start?'),
            ('<>',
                SELECT question_id FROM question WHERE question = 'How does every HTML page start?'),
            ('<div>',
                SELECT question_id FROM question WHERE question = 'How does every HTML page start?'),
            ('1',
                SELECT question_id FROM question WHERE question = 'How many elements can you add the id of "custom-id"?'),
            ('As many as you want',
                SELECT question_id FROM question WHERE question = 'How many elements can you add the id of "custom-id"?'),
            ('0',
                SELECT question_id FROM question WHERE question = 'How many elements can you add the id of "custom-id"?'),
            ('About 3',
                SELECT question_id FROM question WHERE question = 'How many elements can you add the id of "custom-id"?'),
            ('As many as you want',
                SELECT question_id FROM question WHERE question = 'How many elements can you add the class of "custom-class"?'),
            ('1',
                SELECT question_id FROM question WHERE question = 'How many elements can you add the class of "custom-class"?'),
            ('0',
                SELECT question_id FROM question WHERE question = 'How many elements can you add the class of "custom-class"?'),
            ('About 3',
                SELECT question_id FROM question WHERE question = 'How many elements can you add the class of "custom-class"?'),
            ('document.createElement(''div'')',
                SELECT question_id FROM question WHERE question = 'What is the format for creating a div element in JavaScript?'),
            ('file.CreateElement(tagname)',
                SELECT question_id FROM question WHERE question = 'What is the format for creating a div element in JavaScript?'),
            ('document.createDiv()',
                SELECT question_id FROM question WHERE question = 'What is the format for creating a div element in JavaScript?'),
            ('this.createElement(''div''',
                SELECT question_id FROM question WHERE question = 'What is the format for creating a div element in JavaScript?'),
            ('Document Object Model',
                SELECT question_id FROM question WHERE question = 'What does DOM stand for?'),
            ('Document Objective Modeling',
                SELECT question_id FROM question WHERE question = 'What does DOM stand for?'),
            ('Directed Object Method',
                SELECT question_id FROM question WHERE question = 'What does DOM stand for?'),
            ('Displayed Object Middleware',
                SELECT question_id FROM question WHERE question = 'What does DOM stand for?'),
            ('Specify information about the page such as author or keywords',
                SELECT question_id FROM question WHERE question = 'What is a meta tag used for?'),
            ('Can be used to encapsulate a section of data with block level styling',
                SELECT question_id FROM question WHERE question = 'What is a meta tag used for?'),
            ('They are no longer supported as of HTML 5',
                SELECT question_id FROM question WHERE question = 'What is a meta tag used for?'),
            ('Creating an element that will develop superpowers',
                SELECT question_id FROM question WHERE question = 'What is a meta tag used for?'),
            ('<ol> <li>Item 1</li> <li>Item 2</li> <li>Item 3</li> </ol>',
                SELECT question_id FROM question WHERE question = 'Which of these is valid list syntax for creating an ordered list?'),
            ('<ol> <li>Item 1</li> <li>Item 2</li> <li>Item 3</li> </ul>',
                SELECT question_id FROM question WHERE question = 'Which of these is valid list syntax for creating an ordered list?'),
            ('<li> <ol>Item 1</ol> <ol>Item 2</ol> <ol>Item 3</ol> </li>',
                SELECT question_id FROM question WHERE question = 'Which of these is valid list syntax for creating an ordered list?'),
            ('<ul> <li>Item 1</li> <li>Item 2</li> <li>Item 3</li> </ul>',
                SELECT question_id FROM question WHERE question = 'Which of these is valid list syntax for creating an ordered list?'),
            ('<link rel="stylesheet" type="text/css" href="test.css">',
                SELECT question_id FROM question WHERE question = 'How do you link a CSS file?'),
            ('<script rel="stylesheet" type="text/css" href="test.css"></script>',
                SELECT question_id FROM question WHERE question = 'How do you link a CSS file?'),
            ('<script src="test.css"></script>',
                SELECT question_id FROM question WHERE question = 'How do you link a CSS file?'),
            ('<link type="stylesheet" rel="text/css" src="test.css">',
                SELECT question_id FROM question WHERE question = 'How do you link a CSS file?'),
            ('<script src="test.js"></script>',
                SELECT question_id FROM question WHERE question = 'How do you link a JavaScript file?'),
            ('<link rel="script" type="text/css" href="test.js">',
                SELECT question_id FROM question WHERE question = 'How do you link a JavaScript file?'),
            ('<script rel="script" type="text/css" href="test.js"></script>',
                SELECT question_id FROM question WHERE question = 'How do you link a JavaScript file?'),
            ('<link type="script" rel="text/css" src="test.js">',
                SELECT question_id FROM question WHERE question = 'How do you link a JavaScript file?'),

-- CSS 
INSERT INTO question (question, category_id, status_id)
    VALUES ('What does CSS stand for?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('Howt to find elements?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What can you do with element?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What are the Events in css?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is CSS?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('HTML vs css?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is iFrame?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            (' What is DOM?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What tag would you use to create tables?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            (' What tag would you use to create forms?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            (' modules in CSS?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            (' concept of Tweening?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What are CSS counters?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How can we calculate specificity?',
                SELECT category_id FROM question_category WHERE category_name = 'CSS',
                SELECT status_id FROM question_status WHERE status_name = 'Approved')
-- CSS ANSWERS
INSERT INTO answer (answer,question_id)
    VALUES  ('We use the (.)',
                SELECT question_id FROM question WHERE question = 'what do we do To target all elements with specific class attribute in css ?'),
            ('We use the (*)',
                SELECT question_id FROM question WHERE question = 'what do we do To target all elements with specific class attribute in css ?'),
            ('We use the (+)',
                SELECT question_id FROM question WHERE question = 'what do we do To target all elements with specific class attribute in css ?'),
            ('We use the (#)',
                SELECT question_id FROM question WHERE question = 'what do we do To target all elements with specific class attribute in css ?'),
            ('Cross origin resource sharing .',
                SELECT question_id FROM question WHERE question = 'CORS ?'),
            ('cascading origin resource sharing ',
                SELECT question_id FROM question WHERE question = 'CORS ?'),
            ('Cross origin resource system ',
                SELECT question_id FROM question WHERE question = 'CORS ?'),
            ('cascading origin resource system ',
                SELECT question_id FROM question WHERE question = 'CORS ?'),
            ('document . getElementById
            document.getElementByClass',
                SELECT question_id FROM question WHERE question = 'How to find elements ?'),
            ('document . FindElement
            document.getElement',
                SELECT question_id FROM question WHERE question = 'How to find elements ?'),
            ('document . FindElementById
            document.getElementByClass',
                SELECT question_id FROM question WHERE question = 'How to find elements ?'),
            ('document . getElementById
            document.FindElementByClass',
                SELECT question_id FROM question WHERE question = 'How to find elements ?'),
            (' inline : style - attribute . 
            internal : style - tag 
            external : link tag for separate .CSS file .',
                SELECT question_id FROM question WHERE question = 'How to apply CSS : cascading style sheet ?'),
            ('from the html  style - attribute . 
            using css function in html 
            external : link html with external css file .',
                SELECT question_id FROM question WHERE question = 'How to apply CSS : cascading style sheet ?'),
            ('import from functions - attribute . 
            internal : style - tag
            export html link tag for separate .html file .',
                SELECT question_id FROM question WHERE question = 'How to apply CSS : cascading style sheet ?'),
            ('html : style - attribute . 
            css functions 
            external : link html and css in a seperate file .',
                SELECT question_id FROM question WHERE question = 'How to apply CSS : cascading style sheet ?'),
            ('pixels , percent and em.',
                SELECT question_id FROM question WHERE question = 'What values can we give to change the size of an element?'),
            ('size , type and percent',
                SELECT question_id FROM question WHERE question = 'What values can we give to change the size of an element?'),
            ('size , pixels and type',
                SELECT question_id FROM question WHERE question = 'What values can we give to change the size of an element?'),
            ('pixels , type and size',
                SELECT question_id FROM question WHERE question = 'What values can we give to change the size of an element?'),
            ('innerText , innerHTML , appendChild ',
                SELECT question_id FROM question WHERE question = 'What can you do with element in css  ?'),
            ('outerText , outerHTML , appendParent ',
                SELECT question_id FROM question WHERE question = 'What can you do with element in css  ?'),
            ('innerValue , innerCss , appendChild ',
                SELECT question_id FROM question WHERE question = 'What can you do with element in css ?'),
            ('outerValue , innerChild , appendHtml ',
                SELECT question_id FROM question WHERE question = 'What can you do with element in css ?'),
            ('Click , mouseOver , onSubmit , keypass',
                SELECT question_id FROM question WHERE question = 'What is Events in css ?'),
            ('It stores all of the project build files , append the Child',
                SELECT question_id FROM question WHERE question = 'What is Events in css ?'),
            ('It stores the project source files',
                SELECT question_id FROM question WHERE question = 'What is Events in css ?'),
            ('Values',
                SELECT question_id FROM question WHERE question = 'What is Events in css ?'),
            ('Document Object Model',
                SELECT question_id FROM question WHERE question = 'What is DOM ?'),
            ('Document Oriented Model',
                SELECT question_id FROM question WHERE question = 'What is DOM ?'),
            ('Driven Object Model',
                SELECT question_id FROM question WHERE question = 'What is DOM ?'),
            ('Document Ordered Model',
                SELECT question_id FROM question WHERE question = 'What is DOM ?'),
            ('Table Tags Tr  - Th  - Td  ',
                SELECT question_id FROM question WHERE question = 'What tag would you use to create tables ?'),
            ('Table Tags  Td - Tf - Ts  ',
                SELECT question_id FROM question WHERE question = 'What tag would you use to create tables ?'),
            ('Table Tags Ty , Ts ,Tr',
                SELECT question_id FROM question WHERE question = 'What tag would you use to create tables ?'),
            ('Table Tags Tq , Tt ,Th',
                SELECT question_id FROM question WHERE question = 'What tag would you use to create tables ?'),
            (' CSS counters are variables which can be incremented by rules of CSS that inspector track how many times the variable has been used.',
                SELECT question_id FROM question WHERE question = '  What are CSS counters ?'),
            (' CSS counters are row which can be incremented by rules of CSS that inspector track how many times the row has been used.',
                SELECT question_id FROM question WHERE question = '  What are CSS counters ?'),
            (' CSS counters are columns which can be incremented by rules of JavaScript that inspector track how many times the variable has been used.',
                SELECT question_id FROM question WHERE question = '  What are CSS counters ?'),
            (' CSS counters are cells which can be decremented by rules of CSS that inspector track how many times the variable has been used.',
                SELECT question_id FROM question WHERE question = ' What are CSS counters ?'),
            (' To calculate specificity we will start with 0, then we have to add 1000 for each ID and we have to add 10 to the attributes, classes or pseudo-classes with each element name or pseudo-element and later we have to add 1 to them.',
                SELECT question_id FROM question WHERE question = ' How can we calculate specificity ?'),
            (' To calculate specificity we will start with 0, then we have to add 500 for each ID and we have to add 10 to the attributes, classes or pseudo-classes with each element name or pseudo-element and later we have to add 1 to them.',
                SELECT question_id FROM question WHERE question = ' How can we calculate specificity ?'),
            (' To calculate specificity we will start with 0, then we have to add 1000 for each ID and we have to add 50 to the attributes, classes or pseudo-classes with each element name or pseudo-element and later we have to add 1 to them.',
                SELECT question_id FROM question WHERE question = ' How can we calculate specificity ?'),
            (' To calculate specificity we will start with 0, then we have to add 1000 for each ID and we have to add 25 to the attributes, classes or pseudo-classes with each element name or pseudo-element and later we have to add 1 to them.',
                SELECT question_id FROM question WHERE question = ' How can we calculate specificity ?')

-- JS QUESTIONS
INSERT INTO question (question, category_id, status_id)
    VALUES  ('What is JavaScript?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What are JavaScript Data Types?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is the use of isNaN function?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('Between JavaScript and an ASP script, which is faster?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is negative infinity?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('Is it possible to break JavaScript Code into several lines?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('Which company developed JavaScript?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            (' What are undeclared and undefined variables?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is a prompt box?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('  What is 'this' keyword in JavaScript?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('  Which symbol is used for comments in JavaScript?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            (' What is the difference between ViewState and SessionState?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            (' Explain how to read and write a file using JavaScript? ',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What are all the looping structures in JavaScript?',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is called Variable typing in JavaScript??',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('what is the difference between "==" and "==="??',
                SELECT category_id FROM question_category WHERE category_name = 'JavaScript',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
-- JS ANSWERS
INSERT INTO answer (answer,question_id)
    VALUES  ('JavaScript is a client-side as well as server side scripting language that can be inserted into HTML pages and is understood by web browsers. JavaScript is also an Object based Programming language',
                SELECT question_id FROM question WHERE question = 'What is JavaScript ? '),
            ('it is allowing Breaking within a string statement that can be done by the use of a backslash, '\', at the end of the first line',
                SELECT question_id FROM question WHERE question = 'What is JavaScript ? '),
            ('JavaScript is a client-side as well as server side scripting language that can be inserted into HTML pages and is understood by web browsers. JavaScript is Not an Object based Programming language',
                SELECT question_id FROM question WHERE question = 'What is JavaScript ? '),
            ('(for styling) basically  making things look good',
                SELECT question_id FROM question WHERE question = 'What is JavaScript ? '),
            ('Number, String, Boolean, Object, Undefined',
                SELECT question_id FROM question WHERE question = 'What are JavaScript Data Types?'),
            ('long, short, char, Object, Undefined',
                SELECT question_id FROM question WHERE question = 'What are JavaScript Data Types?'),
            ('Number, int, Boolean, Object, Undefined',
                SELECT question_id FROM question WHERE question = 'What are JavaScript Data Types?'),
            ('Number, String, float, Object, Undefined',
                SELECT question_id FROM question WHERE question = 'What are JavaScript Data Types?'),
            ('isNan function returns true if the argument is not a number otherwise it is false',
                SELECT question_id FROM question WHERE question = 'What is the use of isNaN function'),
            ('isNan function returns false if the argument is not a text otherwise it is false',
                SELECT question_id FROM question WHERE question = 'What is the use of isNaN function'),
            ('isNan function returns true if the argument is not a text  otherwise it is false',
                SELECT question_id FROM question WHERE question = 'What is the use of isNaN function'),
            ('isNan function returns false if the argument is not a number otherwise it is false',
                SELECT question_id FROM question WHERE question = 'What is the use of isNaN function'),
            ('isNan function returns true if the argument is not a number otherwise it is false',
                SELECT question_id FROM question WHERE question = 'What is the use of isNaN function'),
            ('JavaScript is Faster. JavaScript is a client-side language and thus it does not need the assistance of the web server to execute. On the other hand, ASP is a server-side language and hence is always slower than JavaScript. ',
                SELECT question_id FROM question WHERE question = 'Between JavaScript and an ASP script, which is faster'),
            ('JavaScript is Slower. JavaScript is a client-side language and thus it does not need the assistance of the web server to execute. On the other hand, ASP is a server-side language and hence is always slower than JavaScript. ',
                SELECT question_id FROM question WHERE question = 'Between JavaScript and an ASP script, which is faster'),
            ('JavaScript is faster. JavaScript is a client-side language and thus it does not need the assistance of the web server to execute. On the other hand, ASP is a client-side language and hence is always slower than JavaScript. ',
                SELECT question_id FROM question WHERE question = 'Between JavaScript and an ASP script, which is faster'),
            ('Negative Infinity is a number in JavaScript which can be derived by dividing negative number by zero',
                SELECT question_id FROM question WHERE question = 'What is negative infinity?'),
            ('Negative Infinity is a number in JavaScript which can be derived by dividing negative number by four',
                SELECT question_id FROM question WHERE question = 'What is negative infinity?'),
            ('Negative Infinity is a number in JavaScript which can be derived by dividing negative number by three',
                SELECT question_id FROM question WHERE question = 'What is negative infinity?'),
            ('Negative Infinity is a number in JavaScript which can be derived by dividing negative number by five ',
                SELECT question_id FROM question WHERE question = 'What is negative infinity?'),
            ('Breaking within a string statement can be done by the use of a backslash, '\', at the end of the first line',
                SELECT question_id FROM question WHERE question = 'Is it possible to break JavaScript Code into several lines ?'),
            ('Breaking within a string statement can be done by the use of a backslash, '\', at the end of the last line',
                SELECT question_id FROM question WHERE question = 'Is it possible to break JavaScript Code into several lines ?'),
            ('Breaking within a string statement can be done by the use of a backslash, '\', at the begining of the first line',
                SELECT question_id FROM question WHERE question = 'Is it possible to break JavaScript Code into several lines ?'),
            ('Netscape is the software company who developed JavaScript',
                SELECT question_id FROM question WHERE question = 'Which company developed JavaScript ? '),
            ('Netflix is the software company who developed JavaScript',
                SELECT question_id FROM question WHERE question = 'Which company developed JavaScript ? '),
            ('Microsoft is the software company who developed JavaScript',
                SELECT question_id FROM question WHERE question = 'Which company developed JavaScript ? '),
            ('Facebook is the software company who developed JavaScript',
                SELECT question_id FROM question WHERE question = 'Which company developed JavaScript ? '),
            ('Undeclared variables are those that do not exist in a program and are not declared. If the program tries to read the value of an undeclared variable, then a runtime error is encountered. AND Undefined variables are those that are declared in the program but have not been given any value. If the program tries to read the value of an undefined variable, an undefined value is returned',
                SELECT question_id FROM question WHERE question = 'What are undeclared and undefined variables ? '),
            ('Undeclared variables are those that do exist in a program and are  declared. If the program tries to read the value of an undeclared variable, then a runtime error is encountered. AND Undefined variables are those that are declared in the program but have not been given any value. If the program tries to read the value of an undefined variable, an undefined value is returned',
                SELECT question_id FROM question WHERE question = 'What are undeclared and undefined variables ? '),
            ('Undeclared variables are those that do not exist in a program and are not declared. If the program tries to read the value of an undeclared variable, then a runtime error is encountered. AND Undefined variables are those that are not declared in the program but have not been given any value. If the program tries to read the value of an undefined variable, an undefined value is not returned',
                SELECT question_id FROM question WHERE question = 'What are undeclared and undefined variables ? '),
            ('Undeclared variables are those that do not exist in a program and are not declared. If the program tries to insert the value of an undeclared variable, then a compile error is encountered. AND Undefined variables are those that are declared in the program but have not been given any value. If the program tries to read the value of an undefined variable, an undefined value is returned',
                SELECT question_id FROM question WHERE question = 'What are undeclared and undefined variables ? '),
            ('A prompt box is a box which allows the user to enter input by providing a text box. Label and box will be provided to enter the text or number',
                SELECT question_id FROM question WHERE question = 'What is a prompt box ?'),
            ('A prompt box is a box which allows the variable  to be entered by providing a text box. Label and box will be to enter that variable ',
                SELECT question_id FROM question WHERE question = 'What is a prompt box ?'),
            ('A way to read and write a file using JavaScript',
                SELECT question_id FROM question WHERE question = 'What is a prompt box ?'),
            ('A way to write and send a file using JavaScript',
                SELECT question_id FROM question WHERE question = 'What is a prompt box ?'),
            ('''This'' keyword refers to the object from where it was called',
                SELECT question_id FROM question WHERE question = 'What is 'this' keyword in JavaScript ?'),
            ('''This'' keyword refers to the object from where it was called',
                SELECT question_id FROM question WHERE question = 'What is 'this' keyword in JavaScript ?'),
            ('''This'' keyword refers to the object from where it was called',
                SELECT question_id FROM question WHERE question = 'What is 'this' keyword in JavaScript ?'),
            ('''This'' keyword refers to the object from where it was called',
                SELECT question_id FROM question WHERE question = 'What is 'this' keyword in JavaScript ?'),
            ('// for Single line comments and /* Multi Line Comment */',
                SELECT question_id FROM question WHERE question = 'Which symbol is used for comments in Javascript ?'),
            ('-- for Single line comments and /* Multi Line Comment */',
                SELECT question_id FROM question WHERE question = 'Which symbol is used for comments in Javascript ?'),
            ('!-- for Single line comments and /* Multi Line Comment */',
                SELECT question_id FROM question WHERE question = 'Which symbol is used for comments in Javascript ?'),
            ('\\ for Single line comments and /-- Multi Line Comment --/',
                SELECT question_id FROM question WHERE question = 'Which symbol is used for comments in Javascript ?'),
            ('''ViewState'' is specific to a page in a session 
            ''SessionState'' is specific to user specific data that can be accessed across all pages in the web application ',
                SELECT question_id FROM question WHERE question = 'What is the difference between ViewState and SessionState ?'),
            ('''ViewState'' is specific to a page in a session 
            ''SessionState'' is specific to server specific data that can be accessed across specific pages in the web application ',
                SELECT question_id FROM question WHERE question = 'What is the difference between ViewState and SessionState ?'),
            ('''ViewState'' is specific to a page in a session 
            ''SessionState'' is the user specific data that can be accessed across all pages in the web application ',
                SELECT question_id FROM question WHERE question = 'What is the difference between ViewState and SessionState ?'),
            ('''ViewState'' is to all the pages in a session 
            ''SessionState'' is specific to user specific data that can be accessed across all pages in the web application ',
                SELECT question_id FROM question WHERE question = 'What is the difference between ViewState and SessionState ?'),
            ('Using JavaScript extensions AND Using a web page and Active X objects',
                SELECT question_id FROM question WHERE question = 'Explain how to read and write a file using JavaScript ?'),
            ('Using java extensions AND Using a web browser and Active X objects',
                SELECT question_id FROM question WHERE question = 'Explain how to read and write a file using JavaScript ?'),
            ('Using JavaScript extensions AND Using a server-side and Active X objects',
                SELECT question_id FROM question WHERE question = 'Explain how to read and write a file using JavaScript ?'),
            ('Using java extensions AND Using a web page and Active X objects',
                SELECT question_id FROM question WHERE question = 'Explain how to read and write a file using JavaScript ?'),
            ('For, While, do-while loops',
                SELECT question_id FROM question WHERE question = 'What are all the looping structures in JavaScript ?'),
            ('For, For-each, do-while loops',
                SELECT question_id FROM question WHERE question = 'What are all the looping structures in JavaScript ?'),
            ('For, Enhanced-For, do-while loops',
                SELECT question_id FROM question WHERE question = 'What are all the looping structures in JavaScript ?'),
            ('For, Enhanced-For, while loops',
                SELECT question_id FROM question WHERE question = 'What are all the looping structures in JavaScript ?'),
            ('Variable typing is used to assign a number to a variable and the same variable can be assigned to a string',
                SELECT question_id FROM question WHERE question = 'What is called Variable typing in Javascript?'),
            ('Variable typing is used to assign a number to a variable and the same variable can be assigned to another number',
                SELECT question_id FROM question WHERE question = 'What is called Variable typing in Javascript?'),
            ('Variable typing is used to enter text with a number to a variable and the same variable can be assigned to a string',
                SELECT question_id FROM question WHERE question = 'What is called Variable typing in Javascript?'),
            ('Variable typing is used to assign a text to a variable and the same variable can be assigned to a number',
                SELECT question_id FROM question WHERE question = 'What is called Variable typing in Javascript?'),
            (' "==" checks only for equality in value whereas "===" is a stricter equality test and returns false if either the value or the type of the two variables are different',
                SELECT question_id FROM question WHERE question = 'what is the difference between "==" and "==="?'' '),
            (' "==" checks only for equality in value whereas "===" is a stricter equality test and returns true if either the value or the type of the two variables are different',
                SELECT question_id FROM question WHERE question = 'what is the difference between "==" and "==="?'' '),
            (' "==" checks only for equality in value whereas "===" is a stricter equality test and returns true if either the value or the type of the two variables are same',
                SELECT question_id FROM question WHERE question = 'what is the difference between "==" and "==="?'' '),
            (' "==" checks only for equality in value whereas "===" is a stricter equality test and returns false if either the value or the type of the two variables are same',
                SELECT question_id FROM question WHERE question = 'what is the difference between "==" and "==="?'' '),

-- DATA STRUCTURE/ALGORITHMS QUESTIONS
INSERT INTO question (question, category_id, status_id)
    VALUES  ('What are data structures?',
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What are some examples of data structures'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How does an array list differ from an array?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How does a linked list differ from an array list?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What makes a hash set different from a tree set?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is a Deque?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is a map/dictionary?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('When would you use a linked list?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('Does a queue have LIFO ordering?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What kinds of characteristics does a tree have?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How about a binary tree?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What do we mean by "Depth First Search"?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How does that differ from "Breadth First Search"?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How do you make a 2D array?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is Big O Notation?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How does spactial complexity differ from temporal complexity?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('In regards to Big O, what''s the best case scenario?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('Define algorithm'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is recursion?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('Recursive answers would be an alternative to what?'
                SELECT category_id FROM question_category WHERE category_name = 'Algorithms',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
-- DATA STRUCTURE/ALGORITHMS ANSWERS
INSERT INTO answer (answer,question_id)
    VALUES  

-- NODE QUESTIONS
INSERT INTO questions(question, category_id, status_id)
    VALUES  ('What is node?',
                SELECT category_id FROM question_category WHERE category_name = 'Node',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What can we do with node?',
                SELECT category_id FROM question_category WHERE category_name = 'Node',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What does NPM stand for?',
                SELECT category_id FROM question_category WHERE category_name = 'Node',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What does NPM do for us?',
                SELECT category_id FROM question_category WHERE category_name = 'Node',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What does the command npm install do?',
                SELECT category_id FROM question_category WHERE category_name = 'Node',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('On what technology is node built on?',
                SELECT category_id FROM question_category WHERE category_name = 'Node',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is package.json?',
                SELECT category_id FROM question_category WHERE category_name = 'Node',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
-- NODE ANSWERS
INSERT INTO answer (answer,question_id)
    VALUES  ('An open-source, cross-platform, runtime environment for JavaScript',
                SELECT question_id FROM question WHERE question = 'What is node?'),
            ('A dynamic JavaScript IDE',
                SELECT question_id FROM question WHERE question = 'What is node?'),
            ('A JavaScript server',
                SELECT question_id FROM question WHERE question = 'What is node?'),
            ('A programming language like JavaScript',
                SELECT question_id FROM question WHERE question = 'What is node?'),
            ('Node.js is a platform that allows JavaScript to be used outside of Web Browsers, for creating web and network applications',
                SELECT question_id FROM question WHERE question = 'What can we do with node?'),
            ('It resolves dependencies in a project',
                SELECT question_id FROM question WHERE question = 'What can we do with node?'),
            ('It compiles JavaScript',
                SELECT question_id FROM question WHERE question = 'What can we do with node?'),
            ('It allows me to create a new node in my project',
                SELECT question_id FROM question WHERE question = 'What can we do with node?'),
            ('Node Package Manager',
                SELECT question_id FROM question WHERE question = 'What does NPM stand for?'),
            ('Node Program Manager',
                SELECT question_id FROM question WHERE question = 'What does NPM stand for?'),
            ('Node Program Module',
                SELECT question_id FROM question WHERE question = 'What does NPM stand for?'),
            ('Node Program Merger',
                SELECT question_id FROM question WHERE question = 'What does NPM stand for?'),
            ('It provides access to hundreds of thousands of reusable packages',
                SELECT question_id FROM question WHERE question = 'What does NPM do for us?'),
            ('It compiles JavaScript',
                SELECT question_id FROM question WHERE question = 'What does NPM do for us?'),
            ('It makes it possible for JavaScript to run in a browser',
                SELECT question_id FROM question WHERE question = 'What does NPM do for us?'),
            ('It turns JavaScript into TypeScript',
                SELECT question_id FROM question WHERE question = 'What does NPM do for us?'),
            ('It installs all modules that are listed in the package.json file and their dependencies',
                SELECT question_id FROM question WHERE question = 'What does the command npm install do?'),
            ('It installs JavaScript',
                SELECT question_id FROM question WHERE question = 'What does the command npm install do?'),
            ('It installs all of the node dependencies',
                SELECT question_id FROM question WHERE question = 'What does the command npm install do?'),
            ('It installs npm and its dependencies',
                SELECT question_id FROM question WHERE question = 'What does the command npm install do?'),
            ('V8 JavaScript runtime',
                SELECT question_id FROM question WHERE question = 'On what technology is node built on?'),
            ('Chrome',
                SELECT question_id FROM question WHERE question = 'On what technology is node built on?'),
            ('Node express',
                SELECT question_id FROM question WHERE question = 'On what technology is node built on?'),
            ('V8',
                SELECT question_id FROM question WHERE question = 'On what technology is node built on?'),
            ('It is a file that contains all of a project''s dependencies',
                SELECT question_id FROM question WHERE question = 'What is package.json?'),
            ('It stores all of the project build files',
                SELECT question_id FROM question WHERE question = 'What is package.json?'),
            ('It stores the project source files',
                SELECT question_id FROM question WHERE question = 'What is package.json?'),
            ('It stores the project object files',
                SELECT question_id FROM question WHERE question = 'What is package.json?'),

-- EXPRESS QUESTIONS
INSERT INTO question (question, category_id, status_id)
    VALUES  ('What is express?',
                SELECT category_id FROM question_category WHERE category_name = 'Express',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('An express application is comprised of what?',
                SELECT category_id FROM question_category WHERE category_name = 'Express',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is middleware?',
                SELECT category_id FROM question_category WHERE category_name = 'Express',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is next() used for?',
                SELECT category_id FROM question_category WHERE category_name = 'Express',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What types of middleware can an express application use?',
                SELECT category_id FROM question_category WHERE category_name = 'Express',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('How do you load router-level middleware?',
                SELECT category_id FROM question_category WHERE category_name = 'Express',
                SELECT status_id FROM question_status WHERE status_name = 'Approved')
-- EXPRESS ANSWERS
INSERT INTO answer (answer,question_id)
    VALUES  ('It is a routing and middleware web framework',
                SELECT question_id FROM question WHERE question = 'What is express?'),
            ('It is a JavaScript server',
                SELECT question_id FROM question WHERE question = 'What is express?'),
            ('It is a TypeScript server',
                SELECT question_id FROM question WHERE question = 'What is express?'),
            ('It is a middleware compiler',
                SELECT question_id FROM question WHERE question = 'What is express?'),
            ('A series of middleware function calls.',
                SELECT question_id FROM question WHERE question = 'An express application is comprised of what?'),
            ('JavaScript files.',
                SELECT question_id FROM question WHERE question = 'An express application is comprised of what?'),
            ('ITypeScript files',
                SELECT question_id FROM question WHERE question = 'An express application is comprised of what?'),
            ('Asynchronous function calls',
                SELECT question_id FROM question WHERE question = 'An express application is comprised of what?'),
            ('A series of functions that have access to the request object (req), the response object (res), and the next middleware function in the application''s request-response cycle.',
                SELECT question_id FROM question WHERE question = 'What is middleware?'),
            ('A series of software components necessary for server creation.',
                SELECT question_id FROM question WHERE question = 'What is middleware?'),
            ('A single function that can communicate with the server',
                SELECT question_id FROM question WHERE question = 'What is middleware?'),
            ('A series of components that connect JavaScript to a database',
                SELECT question_id FROM question WHERE question = 'What is middleware?'),
            ('If the current middleware function does not end the request-response cycle, it must call next() to pass control to the next middleware function.',
                SELECT question_id FROM question WHERE question = 'What is next() used for?'),
            ('It creates the next connection to the database',
                SELECT question_id FROM question WHERE question = 'What is next() used for?'),
            ('It creates the next connection to the server',
                SELECT question_id FROM question WHERE question = 'What is next() used for?'),
            ('It creates the next session instance',
                SELECT question_id FROM question WHERE question = 'What is next() used for?'),
            ('Application-level middleware, Router-level middleware, Error-handling middleware, Built-in middleware, Third-party middleware',
                SELECT question_id FROM question WHERE question = 'What types of middleware can an express application use?'),
            ('Application-level middleware, Router-level middleware, Exception-handling middleware, JavaScript middleware, Third-party middleware',
                SELECT question_id FROM question WHERE question = 'What types of middleware can an express application use?'),
            ('Only express middleware',
                SELECT question_id FROM question WHERE question = 'What types of middleware can an express application use?'),
            ('Only node middleware',
                SELECT question_id FROM question WHERE question = 'What types of middleware can an express application use?'),
            ('By using the router.use() and router.METHOD() functions.',
                SELECT question_id FROM question WHERE question = 'How do you load router-level middleware?'),
            ('By using the router.start() and router.load() functions',
                SELECT question_id FROM question WHERE question = 'How do you load router-level middleware?'),
            ('By using the router.initalize() function',
                SELECT question_id FROM question WHERE question = 'How do you load router-level middleware?'),
            ('By using the router.use() function',
                SELECT question_id FROM question WHERE question = 'How do you load router-level middleware?')

-- REACT QUESTIONS
INSERT INTO questions (question, category_id, status_id)
    VALUES  ('What is React?',
                SELECT category_id FROM question_category WHERE category_name = 'React',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is a SPA?',
                SELECT category_id FROM question_category WHERE category_name = 'React',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is a pure function?',
                SELECT category_id FROM question_category WHERE category_name = 'React',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is JSX/TSX?  What is a JSX template?',
                SELECT category_id FROM question_category WHERE category_name = 'React',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is a component?',
                SELECT category_id FROM question_category WHERE category_name = 'React',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What are properties? ?',
                SELECT category_id FROM question_category WHERE category_name = 'React',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is state in react ?',
                SELECT category_id FROM question_category WHERE category_name = 'React',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is a lifecycle?',
                SELECT category_id FROM question_category WHERE category_name = 'React',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is the render method?',
                SELECT category_id FROM question_category WHERE category_name = 'React',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is React Router?',
                SELECT category_id FROM question_category WHERE category_name = 'React',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is the Controller-View pattern?',
                SELECT category_id FROM question_category WHERE category_name = 'React',
                SELECT status_id FROM question_status WHERE status_name = 'Approved');

-- REACT ANSWERS
INSERT INTO answer (answer,question_id)
    VALUES  

-- REDUX QUESTIONS    
INSERT INTO questions (question, category_id, status_id)
    VALUES  ('What is a mock ?',
                SELECT category_id FROM question_category WHERE category_name = 'Redux',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is a stub ?',
                SELECT category_id FROM question_category WHERE category_name = 'Redux',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('In unit testing, what is a dependency?',
                SELECT category_id FROM question_category WHERE category_name = 'Redux',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('Is Jest only for client side testing ?',
                SELECT category_id FROM question_category WHERE category_name = 'Redux',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is the describe method used to do ?',
                SELECT category_id FROM question_category WHERE category_name = 'Redux',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is ‘expect’ used to do?',
                SELECT category_id FROM question_category WHERE category_name = 'Redux',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('What is Enzyme?',
                SELECT category_id FROM question_category WHERE category_name = 'Redux',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
            ('Why do we need Enzyme ?',
                SELECT category_id FROM question_category WHERE category_name = 'Redux',
                SELECT status_id FROM question_status WHERE status_name = 'Approved'),
-- REDUX ANSWERS
INSERT INTO answer (answer,question_id)
    VALUES  